# apiVersion specifies which version of the Kubernetes API to use.
# 'v1' is the core API version for basic resources like Secrets.
apiVersion: v1
# kind specifies the type of Kubernetes object this manifest creates.
# Here, we are creating a Secret.
kind: Secret
# metadata contains information about the Secret, like its name and labels.
metadata:
  # The name of our Secret object.
  name: webapp-secret
# type: Opaque is the default type for Secrets. It stores arbitrary key-value pairs.
type: Opaque
# stringData is a map of key-value pairs where the values are strings.
stringData:
  DATABASE_URL: 'postgresql://postgres:postgres@db-service:5432/agendog'
